sass:
  style: compressed

exclude:
  - README.md
  - bower.json
  - Gemfile
  - bower_components
  - node_modules
  - Gruntfile.coffee


baseurl: "/debate-ballots"
url: "http://tabbycat-debate.github.io"
